
Random Sampling
Train Epoch: 0 [1/65 (0%)] Loss: 19.939602: : 1it [00:00,  1.10it/s]
Training parameters: {'LOG_DIR': '../Proxy_Anchor/Newlogs', 'dataset': 'cub', 'sz_embedding': 512, 'sz_batch': 90, 'nb_epochs': 40, 'gpu_id': 1, 'nb_workers': 2, 'model': 'bn_inception', 'loss': 'Proxy_Anchor', 'optimizer': 'adamw', 'lr': 0.0001, 'mrg_lr': 0.0005, 'weight_decay': 0.0001, 'weight_lambda': 0.3, 'lr_decay_step': 10, 'lr_decay_gamma': 0.5, 'mrg_lr_decay_step': 10, 'mrg_lr_decay_gamma': 0.5, 'alphap': 48.0, 'alphan': 48.0, 'mrg': 0.1, 'IPC': None, 'warm': 1, 'bn_freeze': 1, 'l2_norm': 1, 'remark': '', 'delta': 0.1, 'T': 1.0, 'lam': 1.0}







Train Epoch: 0 [62/65 (94%)] Loss: 15.608522: : 61it [00:14,  4.35it/s]

Train Epoch: 0 [65/65 (98%)] Loss: 14.744200: : 65it [00:15,  4.09it/s]
Computing t-SNE embedding
  0%|                                                                                                                                                      | 0/2990 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 505, in <module>
    main()
  File "train.py", line 462, in main
    Recalls = utils.evaluate_cos(model, dl_ev)
  File "/home/wyf/Proxy_Anchor/utils.py", line 87, in evaluate_cos
    draw_tsne(X ,path)
  File "/home/wyf/Proxy_Anchor/utils.py", line 212, in draw_tsne
    fig = plot_embedding(result, path)
  File "/home/wyf/Proxy_Anchor/utils.py", line 194, in plot_embedding
    ax1 = fig.add_axes([data[random_arr[i], 0], data[random_arr[i], 1],0.02,0.02])
IndexError: index 15281 is out of bounds for axis 0 with size 5924